# Generated by Django 4.2.4 on 2023-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_company', models.CharField(default='BPI', max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('project_location_name', models.CharField(max_length=255)),
                ('geometry_nodes', models.FloatField()),
                ('project_describtion', models.TextField()),
            ],
        ),
    ]
