# Generated by Django 4.2.4 on 2023-12-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borehole',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='division',
        ),
        migrations.AddField(
            model_name='borehole',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='division_related', to='Projects.division'),
        ),
        migrations.AddField(
            model_name='division',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_related', to='Projects.project'),
        ),
        migrations.AddField(
            model_name='sample',
            name='borehole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borehole_related', to='Projects.borehole'),
        ),
    ]
