# Generated by Django 4.2.4 on 2023-09-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='geometry_nodes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_describtion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
