# Generated by Django 4.2.4 on 2023-12-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_remove_borehole_project_remove_sample_division_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['depth_from']},
        ),
    ]
