# Generated by Django 4.2.4 on 2023-12-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_sample_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='depth_to',
            field=models.FloatField(),
        ),
    ]
