# Generated by Django 4.2.5 on 2024-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_division_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='borehole',
            name='slug',
            field=models.SlugField(default='-'),
        ),
        migrations.AddField(
            model_name='sample',
            name='random_string',
            field=models.CharField(blank=True, default='riWtZysA2M', editable=False, max_length=10),
        ),
    ]
