# Generated by Django 4.2.5 on 2024-03-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_borehole_slug_sample_random_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='slug',
            field=models.SlugField(default='-'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='random_string',
            field=models.CharField(blank=True, default='ObLySNqpe4', editable=False, max_length=10),
        ),
    ]
