# Generated by Django 4.2.5 on 2024-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_sample_random_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='random_string',
            field=models.CharField(blank=True, default='sKWJRkmHKM', editable=False, max_length=10),
        ),
    ]
