# Generated by Django 4.2.4 on 2024-04-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight_tin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wet_weight_tin_soil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dry_weight_tin_soil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borehole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.borehole')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.division')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.sample')),
            ],
        ),
    ]
