# Generated by Django 4.2.5 on 2024-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaterContent', '0002_alter_watercontent_sample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='watercontent',
            unique_together=set(),
        ),
    ]
