# Generated by Django 4.2.5 on 2024-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaterContent', '0003_ajaxtest_alter_watercontent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercontent',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
